<?php
// $Id$

	/******************************************************************************
	 * Hooks
	 *****************************************************************************/

	/**
	 * Implementation of hook_init().
	 */
	function mnnmisc_init() {
	}

	/*
	 * Implementation of hook_help().
	 */
	function mnnmisc_help($path, $arg) {
		if ($path == 'admin/help#mnnmisc') {
			$output = '<p>' . t('') . '</p>';
			return $output;
		}
	}

	/**
	 * Implementation of hook_block().
	 */
	function mnnmisc_block($op = 'list', $delta = 0, $edit = array()) {
		switch ($op) {
			case 'list':
				$blocks[0]['info'] = t('News Archive');
				$blocks[0]['cache'] = BLOCK_NO_CACHE;

				$blocks[1]['info'] = t('YC News Archive');
				$blocks[1]['cache'] = BLOCK_NO_CACHE;

				$blocks[2]['info'] = t('Watch Live Embed');
				$blocks[2]['cache'] = BLOCK_NO_CACHE;

				return $blocks;

			case 'view':
				if ($delta == 0) {
					$block['subject'] = t('Archive');
					$block['content'] = _mnnmisc_block_news_archive();
				}
				elseif ($delta == 1) {
					$block['subject'] = t('Archives');
					$block['content'] = _mnnmisc_block_yc_news_archive();
				}
				elseif ($delta == 2) {
					$block['content'] = _mnnmisc_block_watch_live_embed_code();
				}

				return $block;
		}

	}

	/******************************************************************************
	 * Other Public Functions
	 *****************************************************************************/

	/******************************************************************************
	 * Helper Functions
	 *****************************************************************************/

	function _mnnmisc_block_news_archive(){
		drupal_add_js(drupal_get_path('module', 'mnnmisc').'/mnnmisc.js');
		$query = 'SELECT DATE_FORMAT(FROM_UNIXTIME(n.created), "%Y") AS `year`, DATE_FORMAT(FROM_UNIXTIME(n.created), "%m") AS `month` ';
		$query .= 'FROM {node} n ';
		$query .= 'WHERE (n.status <> 0) AND (n.type in ("news")) ';
		$query .= 'ORDER BY `year` DESC, `month` DESC';

		$result = db_query(db_rewrite_sql($query));
		$ym = array();
		while ($months = db_fetch_object($result)) {
			$ym[$months->year][$months->month] = $ym[$months->year][$months->month] + 1;
		}

		$a_date = new DateTime('1/1/2000 12:00:00');
		$content = '<ul class="news-archive">';
		foreach ($ym AS $year => $months){
			$inner = '<ul>';
			$counter = 0;
			foreach ($months AS $month => $num_per_month){
				$a_date->setDate($year, $month, 1);
				$inner .= '<li><a href="/news/archive/'.$year.$month.'">'.$a_date->format('F').'</a> ('.$num_per_month.')</li>';
				$counter += $num_per_month;
			}
			$inner .= '</ul>';
			$a_date->setDate($year, 1, 1);
			$content .= '<li class="year collapsed"><a href="#">'.$a_date->format('Y').'</a> ('.$counter.') '.$inner.'</li>';
		}
		$content .= '</ul>';

		return $content;
	}

	function _mnnmisc_block_yc_news_archive(){
		drupal_add_js(drupal_get_path('module', 'mnnmisc').'/mnnmisc.js');
		$query = 'SELECT DATE_FORMAT(FROM_UNIXTIME(n.created), "%Y") AS `year`, DATE_FORMAT(FROM_UNIXTIME(n.created), "%m") AS `month` ';
		$query .= 'FROM {node} n ';
		$query .= 'WHERE (n.status <> 0) AND (n.type in ("yc_news")) ';
		$query .= 'ORDER BY `year` DESC, `month` DESC';

		$result = db_query(db_rewrite_sql($query));
		$ym = array();
		while ($months = db_fetch_object($result)) {
			$ym[$months->year][$months->month] = $ym[$months->year][$months->month] + 1;
		}

		$a_date = new DateTime('1/1/2000 12:00:00');
		$content = '<ul class="news-archive">';
		foreach ($ym AS $year => $months){
			$inner = '<ul>';
			$counter = 0;
			foreach ($months AS $month => $num_per_month){
				$a_date->setDate($year, $month, 1);
				$inner .= '<li><a href="/youth-channel/news/archive/'.$year.$month.'">'.$a_date->format('F').'</a> ('.$num_per_month.')</li>';
				$counter += $num_per_month;
			}
			$inner .= '</ul>';
			$a_date->setDate($year, 1, 1);
			$content .= '<li class="year collapsed"><a href="#">'.$a_date->format('Y').'</a> ('.$counter.') '.$inner.'</li>';
		}
		$content .= '</ul>';

		return $content;
	}

  function _mnnmisc_block_watch_live_embed_code(){
    $url = (!empty($_SERVER['HTTPS']))
      ? "https://".$_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI']
      : "http://".$_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI'];
    $embed_code = '<iframe src="'. $url .'?iframe=1" frameborder="0" width="600" height="334" scrolling="no" allowfullscreen></iframe>';
    $embed_code = htmlspecialchars($embed_code);

    $content = "<a href='#' class='modal-trigger watch-live-button' data-modal-element='video-embed-code'>Embed this video</a>";
    $content .= "<div id='video-embed-code'>";
    $content .= "<h3>Embed this video</h3>";
    $content .= "<h5>Copy the embed code below, and paste it to your website.</h5>";
    //$content .= '<div contenteditable="true" class="embed-code" spellcheck="false">'. $embed_code .'</div>';
    $content .= '<textarea class="embed-code select-all" spellcheck="false">'. $embed_code .'</textarea>';
    //$content .= $embed_code;
    $content .= "</div> ";

    return $content;
  }
