<?php
// $Id$

	/******************************************************************************
	 * Hooks
	 *****************************************************************************/

	/**
	 * Implementation of hook_init().
	 */
	function mnnmisc_init() {
	}

	/*
	 * Implementation of hook_help().
	 */
	function mnnmisc_help($path, $arg) {
		if ($path == 'admin/help#mnnmisc') {
			$output = '<p>' . t('') . '</p>';
			return $output;
		}
	}

	/**
	 * Implementation of hook_block().
	 */
	function mnnmisc_block($op = 'list', $delta = 0, $edit = array()) {
		switch ($op) {
			case 'list':
				$blocks[0]['info'] = t('News Archive');
				$blocks[0]['cache'] = BLOCK_NO_CACHE;

				return $blocks;

			case 'view':
				if ($delta == 0) {
					$block['subject'] = t('Archive');
					$block['content'] = _mnnmisc_block_news_archive();
				}

				return $block;
		}

	}

	/******************************************************************************
	 * Other Public Functions
	 *****************************************************************************/

	/******************************************************************************
	 * Helper Functions
	 *****************************************************************************/

	function _mnnmisc_block_news_archive(){
		drupal_add_js(drupal_get_path('module', 'mnnmisc').'/mnnmisc.js');
		$query = 'SELECT DATE_FORMAT(FROM_UNIXTIME(n.created), "%Y") AS `year`, DATE_FORMAT(FROM_UNIXTIME(n.created), "%m") AS `month` ';
		$query .= 'FROM {node} n ';
		$query .= 'WHERE (n.status <> 0) AND (n.type in ("news")) ';
		$query .= 'ORDER BY `year` DESC, `month` DESC';

		$result = db_query(db_rewrite_sql($query));
		$ym = array();
		while ($months = db_fetch_object($result)) {
			$ym[$months->year][$months->month] = $ym[$months->year][$months->month] + 1;
		}

		$a_date = new DateTime('1/1/2000 12:00:00');
		$content = '<ul class="news-archive">';
		foreach ($ym AS $year => $months){
			$inner = '<ul>';
			$counter = 0;
			foreach ($months AS $month => $num_per_month){
				$a_date->setDate($year, $month, 1);
				$inner .= '<li><a href="/news/archive/'.$year.$month.'">'.$a_date->format('F').'</a> ('.$num_per_month.')</li>';
				$counter += $num_per_month;
			}
			$inner .= '</ul>';
			$a_date->setDate($year, 1, 1);
			$content .= '<li class="year collapsed"><a href="#">'.$a_date->format('Y').'</a> ('.$counter.') '.$inner.'</li>';
		}
		$content .= '</ul>';

		return $content;
	}

