<?php
// $Id$

	/******************************************************************************
	 * Hooks
	 *****************************************************************************/

	/**
	 * Implementation of hook_init().
	 */
	function mnnshow_init() {
	}

	/*
	 * Implementation of hook_help().
	 */
	function mnnshow_help($path, $arg) {
		if ($path == 'admin/help#mnnshow') {
			$output = '<p>' . t('') . '</p>';
			return $output;
		}
	}

	/**
	 * Implementation of hook_menu().
	 */
	function mnnshow_menu() {
		$items['shows/past-shows/category'] = array(
			'title' => 'Shows',
			'page callback' => 'mnnshow_show_list_past_by_category',
			'page arguments' => array(3),
			'access arguments' => array('access content')
		);
		$items['shows/past-shows'] = array(
			'title' => 'Shows',
			'page callback' => 'mnnshow_show_list_past_by_alpha',
			'page arguments' => array(2),
			'access arguments' => array('access content')
		);
		$items['shows/category'] = array(
			'title' => 'Shows',
			'page callback' => 'mnnshow_show_list_current_by_category',
			'page arguments' => array(2),
			'access arguments' => array('access content')
		);
		$items['shows'] = array(
			'title' => 'Shows',
			'page callback' => 'mnnshow_show_list_current_by_alpha',
			'page arguments' => array(1),
			'access arguments' => array('access content')
		);
		$items['show-info/%'] = array(
			'title' => 'Show Info',
			'page callback' => 'mnnshow_show_info',
			'page arguments' => array(1),
			'access arguments' => array('access content')
		);
		$items['schedule'] = array(
			'title' => 'Schedule',
			'page callback' => 'mnnshow_schedule',
			'access arguments' => array('access content')
		);
		$items['schedule/get'] = array(
			'page callback' => 'mnnshow_schedule_get',
			'access arguments' => array('access content'),
			'type' => MENU_CALLBACK
		);
		$items['schedule/header'] = array(
			'page callback' => 'mnnshow_schedule_table_header',
			'access arguments' => array('access content'),
			'type' => MENU_CALLBACK
		);

		return $items;
	}

	/**
	 * Page callback.
	 */
	function mnnshow_show_list_past_by_category($category) {
		if (!$category) {
			$category = "all";
			$display_category = 'All';
		}
		else {
			$categories = _mnnshow_get_categories();
			if (array_key_exists($category, $categories)) {
				$display_category = $categories[$category];
			}
			else {
				$category = "all";
				$display_category = 'All';
			}
		}

		if ($category == 'all'){
			$topic = '';
		}
		else {
			$topic = ' AND s.topic = "'. $display_category .'"';
		}

		$project_status = 's.project_status = "Archival" OR s.project_status = "Completed" OR s.project_status = "Cancelled" OR s.project_status = "Withdrawn"';

		$query = 'SELECT s.project_id, s.title ';
		$query .= 'FROM {ac_report_project_cache} s WHERE ( '.$project_status.' )'.$topic.' ORDER BY s.title ASC';

		$count_query = 'SELECT COUNT(*) FROM ('. $query .') AS count_query';

		return _mnnshow_show_past_list($query, $count_query, $display_category);
	}

	/**
	 * Page callback.
	 */
	function mnnshow_show_list_past_by_alpha($char) {
		if (!$char)
			$char = "a";
		else {
			$char = substr(strtolower($char), 0, 1); // first lowercase character
			if (!ctype_alpha($char))
				$char = 'a';
		}

		$project_status = 's.project_status = "Archival" OR s.project_status = "Completed" OR s.project_status = "Cancelled" OR s.project_status = "Withdrawn"';
		
		$query = 'SELECT s.project_id, s.title ';
		$query .= 'FROM {ac_report_project_cache} s WHERE ( '.$project_status.' ) ';
		$query .= 'AND s.title LIKE "'.$char.'%" ORDER BY s.title ASC';

		$count_query = 'SELECT COUNT(*) FROM ('. $query .') AS count_query';

		return _mnnshow_show_past_list($query, $count_query, strtoupper($char));
	}

	/**
	 * Page callback.
	 */
	function mnnshow_show_list_current_by_category($category) {
		if (!$category) {
			$category = "all";
			$display_category = 'All';
		}
		else {
			$categories = _mnnshow_get_categories();
			if (array_key_exists($category, $categories)) {
				$display_category = $categories[$category];
			}
			else {
				$category = "all";
				$display_category = 'All';
			}
		}


		$query = 'SELECT s.project_id, s.title, s.narrative AS description, s.topic, s.project_status, MIN(a.start_time) AS start_time, a.channel ';
		$query .= 'FROM {ac_report_project_cache} s ';
		$query .= 'JOIN {ac_report_episode_cache} e ON s.project_id = e.project_id ';
		$query .= 'JOIN {ac_report_airing_cache} a ON e.episode_id = a.episode_id ';
		$query .= 'WHERE (s.project_status = "Active" OR s.project_status = "Completed") ';
		$query .= 'AND a.start_time > NOW() ';
		if ($category != 'all'){
			$query .= ' AND s.topic = "'. $display_category .'"';
		}
		$query .= 'GROUP BY s.title ';
		$query .= 'ORDER BY s.title ASC ';

		$count_query = 'SELECT COUNT(*) FROM ('. $query .') AS count_query';

		return _mnnshow_show_current_list($query, $count_query, $display_category);
	}

	/**
	 * Page callback.
	 */
	function mnnshow_show_list_current_by_alpha($char) {
		if (!$char)
			$char = "a";
		else {
			$char = substr(strtolower($char), 0, 1); // first lowercase character
			if (!ctype_alpha($char))
				$char = 'a';
		}

		$query = 'SELECT s.project_id, s.title, s.narrative AS description, s.topic, s.project_status, MIN(a.start_time) AS start_time, a.channel ';
		$query .= 'FROM {ac_report_project_cache} s ';
		$query .= 'JOIN {ac_report_episode_cache} e ON s.project_id = e.project_id ';
		$query .= 'JOIN {ac_report_airing_cache} a ON e.episode_id = a.episode_id ';
		$query .= 'WHERE (s.project_status = "Active" OR s.project_status = "Completed") ';
		$query .= 'AND a.start_time > NOW() ';
		$query .= 'AND s.title LIKE "'.$char.'%" ';
		$query .= 'GROUP BY s.title ';
		$query .= 'ORDER BY s.title ASC ';

		$count_query = 'SELECT COUNT(*) FROM ('. $query .') AS count_query';

		return _mnnshow_show_current_list($query, $count_query, NULL);
	}

	/**
	 * Page callback.
	 */
	function mnnshow_show_info($id) {
		if (!is_numeric($id)) {
			return null;
		}

		$query = 'SELECT s.project_id, s.title, s.narrative AS description, s.topic, s.project_status, s.public_url, ';
		$query .= '( SELECT a.start_time FROM {ac_report_airing_cache} AS a JOIN {ac_report_episode_cache} AS e ON e.episode_id = a.episode_id ';
		$query .= 'WHERE s.project_id = e.project_id AND a.start_time > NOW() ORDER BY a.start_time LIMIT 1 ) AS start_time, ';
		$query .= '( SELECT a.channel FROM {ac_report_airing_cache} AS a JOIN {ac_report_episode_cache} AS e ON e.episode_id = a.episode_id ';
		$query .= 'WHERE s.project_id = e.project_id AND a.start_time > NOW() ORDER BY a.start_time LIMIT 1 ) AS channel ';
		$query .= 'FROM {ac_report_project_cache} s WHERE s.project_id = "'.$id.'"';

		$result = db_query($query);
		//$count = 0;
		$content = '';
		while ($row = db_fetch_object($result)) {
			$title = $row->title; // ucwords(strtolower($row->title));
			drupal_set_title($title);
			$content .= '<div class="category">'. $row->topic .'</div>';
			$content .= '<div class="meta"><span class="channel">'. $row->channel .'</span>';
			if ($row->start_time){
				$start_time = new DateTime($row->start_time, new DateTimeZone('America/New_York'));
				$content .= '<span class="next-airing">Next Airing: '. $start_time->format("D, M j, Y \a\\t g:ia T") .'</span></div>';
			}
			else {
				$content .= '<span class="next-airing">Next Airing: There are no scheduled airings for this show.</span></div>';
			}
			$content .= '<div class="content">' . $row->description . '</div>';
			if ($row->public_url){
				$content .= '<div class="website"><span class="label">Website: </span><a href="'. $row->public_url .'">'. $row->public_url .'</a></div>';
			}
		}
		return $content;
	}

	/**
	 * Page callback.
	 */
	function mnnshow_schedule(){
		jquery_ui_add('ui.datepicker');
		drupal_add_js(drupal_get_path('module', 'mnnshow').'/mnnshow.js');
		$content = '<div id="schedule"><header id="schedule-header"><div class="inner"><div class="nav"></div><div class="channels"></div></div></header><div id="cols"></div></div> ';
		return $content;
	}
	
	/**
	 * Page callback.
	 */
	function mnnshow_schedule_get(){
//		$requested_date = new DateTime('6/1/2011', new DateTimeZone('America/New_York'));
		try {
			$requested_date = new DateTime($_POST['date'], new DateTimeZone('America/New_York'));
		} catch (Exception $e) {
			$requested_date = new DateTime(NULL, new DateTimeZone('America/New_York'));
		}

		$query = 'SELECT s.project_id, s.title, s.topic, a.start_time, a.duration, a.channel ';
		$query .= 'FROM {ac_report_project_cache} s ';
		$query .= 'LEFT JOIN {ac_report_episode_cache} e ON s.project_id = e.project_id ';
		$query .= 'LEFT JOIN {ac_report_airing_cache} a ON e.episode_id = a.episode_id ';
		$query .= 'WHERE (a.start_time >= "'.$requested_date->format('Y-m-d').' 0:00:00" AND a.start_time <= "'.$requested_date->format('Y-m-d').' 23:59:59") ';
		$query .= 'OR (a.end_time >= "'.$requested_date->format('Y-m-d').' 0:00:00" AND a.end_time <= "'.$requested_date->format('Y-m-d').' 23:59:59") ';
		$query .= 'ORDER BY a.channel ASC, a.start_time ASC';

		$result = db_query(db_rewrite_sql($query));
		$ch1 = array();
		$ch2 = array();
		$ch3 = array();
		$ch4 = array();
		while ($data = db_fetch_object($result)) {
			$duration = $data->duration / 60;
			$duration = round($duration / 30) * 30; // round to nearest 30
			$start = new DateTime($data->start_time, new DateTimeZone('America/New_York'));
			$end = new DateTime($data->start_time, new DateTimeZone('America/New_York'));
			$end->add(new DateInterval('PT'.$duration.'M'));
			$now = new DateTime(NULL, new DateTimeZone('America/New_York'));
			$midnight = new DateTime($requested_date->format('m/d/Y 0:0:0'), new DateTimeZone('America/New_York'));
			if ($start < $midnight){
				$interval = $start->diff($midnight);
				$duration -= intval($interval->format('%i'));
			}
			if ($now >= $start && $now <= $end)
				$current = 'true';
			else
				$current = 'false';
			$row = array(
				'link' => '/show-info/'.$data->project_id.'/'._mnnshow_url_feiendly_title($data->title),
				'title' => $data->title,
				'category' => isset($data->topic) ? $data->topic : '',
				'start' => $start->format("H-i"),
				'isCurrent' => $current,
				'duration' => $duration
			);
			switch ($data->channel){
				case 'Channel 1':
					$ch1[] = $row;
					break;
				case 'Channel 2':
					$ch2[] = $row;
					break;
				case 'Channel 3':
					$ch3[] = $row;
					break;
				case 'Channel 4':
					$ch4[] = $row;
					break;
			}
			//print_r($row);
		}

		// time column
		$time_col = array();
		$now = new DateTime(NULL, new DateTimeZone('America/New_York'));
		$hour = $now->format('H');
		$minute = $now->format('i') >= 30 ? '30' : '00';
		$now->setTime($hour, $minute, 0); // round down to nearest half hour

		$time_increment = clone $requested_date;
		$time_increment->setTime(0, 0, 0);
		for ($i = 0; $i < 48; $i++){
			$time_increment == $now ? $current = 'true' : $current = 'false';
			$time_col[] = array(
				'display' => $time_increment->format('g:i A'),
				'isCurrent' => $current
			);
			$time_increment->add(new DateInterval('PT30M'));
		}

		// dates
		$prevDate = clone $requested_date;
		$nextDate = clone $requested_date;
		$prevDate->sub(new DateInterval('P1D'));
		$nextDate->add(new DateInterval('P1D'));

		drupal_set_header('Content-Type: application/json');
		drupal_json(array(
			            'schedDate' => $requested_date->format('m/d/Y'),
			            'prevDate' => $prevDate->format('m/d/Y'),
			            'nextDate' => $nextDate->format('m/d/Y'),
			            'displayDate' => $requested_date->format('l, F j'),
			            'time' => $time_col,
			            'ch1' => $ch1,
			            'ch2' => $ch2,
			            'ch3' => $ch3,
			            'ch4' => $ch4
		            ));
		exit();
	}

	/**
	 * Page callback.
	 */
	function mnnshow_schedule_table_header(){
		$channels = mnnshow_get_channels();
		//print_r($channels);
		
		drupal_set_header('Content-Type: application/json');
		drupal_json(array(
			            'channel1' => $channels['1'],
			            'channel2' => $channels['2'],
			            'channel3' => $channels['3'],
			            'channel4' => $channels['4']
		            ));
		exit();
	}

	/**
	 * Implementation of hook_block().
	 */
	function mnnshow_block($op = 'list', $delta = 0, $edit = array()) {
		switch ($op) {
			case 'list':
				$blocks[0]['info'] = t('Show Producer Info');
				$blocks[0]['cache'] = BLOCK_NO_CACHE;

				$blocks[1]['info'] = t('Shows Filters Heading');
				$blocks[1]['cache'] = BLOCK_NO_CACHE;

				$blocks[2]['info'] = t('Watch Now');
				$blocks[2]['cache'] = BLOCK_NO_CACHE;

				return $blocks;

			case 'view':
				if ($delta == 0) {
					$block['subject'] = t('About the Producer');
					$block['content'] = _mnnshow_block_publisher_info();
				}
				elseif ($delta == 1){
					$block['content'] = _mnnshow_block_shows_filter();
				}
				elseif ($delta == 2){
					$block['content'] = _mnnshow_block_watch_now();
				}

				return $block;
		}

	}

	/**
	 * Implementation of hook_update_index().
	 */
	function mnnshow_update_index() {
		// We define these variables as global so our shutdown function can
		// access them.
		global $mnnshow_last_change, $mnnshow_last_id;

		// If PHP times out while indexing, run a function to save
		// information about how far we got so we can continue at next cron run.
		register_shutdown_function('mnnshow_update_shutdown');
		$mnnshow_last_id = variable_get('mnnshow_cron_last_id', 0);
		$mnnshow_last_change = variable_get('mnnshow_cron_last_change', 0);

		$query = 'SELECT s.project_id, s.title, s.narrative AS description, UNIX_TIMESTAMP(s.changed) AS changed, p.display_name ';
		$query .= 'FROM {ac_report_project_cache} s ';
		$query .= 'LEFT JOIN {ac_report_producer_cache} p ';
		$query .= 'ON s.exec_producer_id = p.producer_id ';
		$query .= 'WHERE (s.project_id > %d) OR (s.changed > %d) ';
		$query .= 'ORDER BY s.changed ASC';
		$result = db_query($query, $mnnshow_last_id, $mnnshow_last_change);

		// Feed the external information to the search indexer.
		while ($data = db_fetch_object($result)) {
			$mnnshow_last_change = $data->changed;
			$mnnshow_last_id = $data->project_id;
			$text = '<h1>' . check_plain($data->title) . '</h1><h4>' . $data->display_name . '</h4>' . $data->description;
			search_index($data->project_id, 'mnnshow', $text);
		}
	}

	/**
	 * Implementation of hook_search().
	 */
	function mnnshow_search($op = 'search', $keys = NULL) {
		switch ($op) {
			case 'name':
				return t('Shows'); // Used on search tab.
			case 'reset':
				variable_del('mnnshow_cron_last_id');
				variable_del('mnnshow_cron_last_change');
				return;
			case 'search':
				// Search the index for the keywords that were entered.
				$hits = do_search($keys, 'mnnshow');
				$results = array();
				// We now have the IDs of the results. Pull each result
				// from the legacy database.
				foreach ($hits as $item) {
					$query = 'SELECT s.project_id, s.title, s.narrative AS description, UNIX_TIMESTAMP(s.changed) AS changed, p.display_name ';
					$query .= 'FROM {ac_report_project_cache} s ';
					$query .= 'LEFT JOIN {ac_report_producer_cache} p ';
					$query .= 'ON s.exec_producer_id = p.producer_id ';
					$query .= 'WHERE s.project_id = %d';
					$show = db_fetch_object(db_query($query, $item->sid));
					$results[] = array(
						'link' => url(_mnnshow_get_show_href($show->title, $item->sid), array('absolute' => 'true')),
						'type' => t('Show'),
						'title' => $show->title,
						'date' => $show->changed,
						'score' => $item->score,
						'snippet' => search_excerpt($keys, $show->description));
				}
				return $results;
		}
	}
	
	/******************************************************************************
	 * Other Public Functions
	 *****************************************************************************/

	function mnnshow_get_channels(){
		// check for cached channels
		if ($cached = cache_get('mnnshow:channels', 'cache')) {
			return $cached->data;
		}

		$channels = array();

		$result = db_query("SELECT nid FROM {node} WHERE type = 'channel_info'");
		while($row = db_fetch_object($result)) {
			$channel_info = node_load($row->nid); // drupal content type
			$tv_ch = array();
			foreach ($channel_info->field_television_channel as $tv_ch_nid){
				$television_channel = node_load($tv_ch_nid['nid']); // drupal content type
				$television_station = node_load($television_channel->field_television_station[0]['nid']); // drupal content type
				$tv_ch[] = array(
					'tvStationName' => $television_station->title,
					'tvStationChannel' => $television_channel->field_channel_number[0]['value']
				);
			}
			$channels[$channel_info->field_number[0]['value']] = array(
				'name' => $channel_info->title,
				'description' => $channel_info->body,
				'watchLiveUrl' => drupal_get_path_alias('node/'.$channel_info->field_watch_live_link[0]['nid']),
				'tvChannels' => $tv_ch
			);
		}

		// store in cache with a minimum expiration time of 1 day
		cache_set('mnnshow:channels', $channels, 'cache', time() + (60 * 60 * 24));
		return $channels;
	}

	/**
	 * Search shutdown function to make sure we remember the last element processed.
	 */
	function mnnshow_update_shutdown() {
		global $mnnshow_last_change, $mnnshow_last_id;
		if ($mnnshow_last_change && $mnnshow_last_id) {
			variable_set('mnnshow_cron_last_id', $mnnshow_last_id);
			variable_set('mnnshow_cron_last_change', $mnnshow_last_change);
		}
	}

	function mnnshow_current_show_info($channelNum){
		if (!is_numeric($channelNum)) {
			return null;
		}

		$now = new DateTime(NULL, new DateTimeZone('America/New_York'));
		//$now = new DateTime('2011-05-15 19:25', new DateTimeZone('America/New_York'));
		$query = 'SELECT s.project_id, s.title, s.narrative AS description, s.topic, s.project_status, s.public_url, a.channel ';
		$query .= 'FROM {ac_report_project_cache} s ';
		$query .= 'LEFT JOIN {ac_report_episode_cache} e ON s.project_id = e.project_id ';
		$query .= 'LEFT JOIN {ac_report_airing_cache} a ON e.episode_id = a.episode_id ';
		$query .= 'WHERE a.start_time <= "'.$now->format('Y-m-d G:i:s').'" ';
		$query .= 'AND a.end_time >= "'.$now->format('Y-m-d G:i:s').'" ';
		$query .= 'AND a.channel ="Channel '.$channelNum.'" ';

		$result = db_query($query);
			//$count = 0;
		while ($row = db_fetch_object($result)) {
			return array(
				'title' => $row->title,
				'category' => $row->topic,
				'description' => $row->description,
				'url' => $row->public_url
			);
		}
	}

	/******************************************************************************
	 * Helper Functions
	 *****************************************************************************/

	function _mnnshow_block_watch_now(){
		$channel_info = mnnshow_get_channels();
		$channels = array();

		$now = new DateTime(NULL, new DateTimeZone('America/New_York'));
		//$now = new DateTime('2011-05-15 19:25', new DateTimeZone('America/New_York'));
		$query = 'SELECT s.project_id, s.title, a.channel ';
		$query .= 'FROM {ac_report_project_cache} s ';
		$query .= 'LEFT JOIN {ac_report_episode_cache} e ON s.project_id = e.project_id ';
		$query .= 'LEFT JOIN {ac_report_airing_cache} a ON e.episode_id = a.episode_id ';
		$query .= 'WHERE (a.start_time <= "'.$now->format('Y-m-d G:i:s').'" AND DATE_ADD(a.end_time, INTERVAL 2 MINUTE) >= "'.$now->format('Y-m-d G:i:s').'") ';
		$query .= 'ORDER BY a.channel ASC';

		$result = db_query(db_rewrite_sql($query));
		while ($data = db_fetch_object($result)) {
			$show = array(
				'id' => $data->project_id,
				'title' => $data->title,
				'url' => _mnnshow_get_show_href($data->title, $data->project_id)
			);
			switch ($data->channel){
				case 'Channel 1':
					if (!isset($channels[1]))
						$channels[1] = $show;
					break;
				case 'Channel 2':
					if (!isset($channels[2]))
						$channels[2] = $show;
					break;
				case 'Channel 3':
					if (!isset($channels[3]))
						$channels[3] = $show;
					break;
				case 'Channel 4':
					if (!isset($channels[4]))
						$channels[4] = $show;
					break;
			}
		}

		$content = "<div class='whats-on-now'>";
		$content .= "<h3>What's on Now</h3>";
		$content .= "<time>".$now->format('M j, Y g:i a')."</time>";
		$content .= "<p class='view-sched'><a href='/schedule'>View Schedule</a></p>";
		$content .= "</div>";
		
		$content .= "<ul>";
		for ($i = 1; $i <= 4; $i++){
			$content .= '<li id="channel'.$i.'"><div class="channel-info">';
			$content .= '<h4>'.$channel_info[$i]['name'].'</h4>';
			$content .= '<h5><a href="/'.$channel_info[$i]['watchLiveUrl'].'">'.$channels[$i]['title'].'</h5>';
			$content .= '<p class="watch-now-link"><a href="/'.$channel_info[$i]['watchLiveUrl'].'">Watch Now</a></p>';
			$content .= "<div class='channel-about'>";
			$content .= "<p class='channel-description'>".$channel_info[$i]['description']."</p>";
			$content .= "<ul class='cable-channel-list'>";
			foreach ($channel_info[$i]['tvChannels'] as $tvStation){
				$content .= '<li>'.$tvStation['tvStationName'].'<span class="cable-number"">'.$tvStation['tvStationChannel'].'</span></li>';
			}
			$content .= "</ul>";
			$content .= "</div>";
			$content .= "</div>";
			$content .= "</li>";
		}
		$content .= "</ul>";

		return $content;
	}

	function _mnnshow_block_shows_filter(){
		$path = drupal_get_path_alias($_GET['q']);
		$path = explode('/', $path);
		if ($path[0] == 'shows' && $path[1] == 'past-shows' && $path[2] == 'category') { // past shows with category
			$is_current_shows = false;
			$is_alphabetical = false;
			if ($path[3])
				$current_category = $path[3];
			else
				$current_category = '';
		}
		elseif ($path[0] == 'shows' && $path[1] == 'past-shows') { // past shows alphabetical
			$is_current_shows = false;
			$is_alphabetical = true;
			if ($path[2])
				$current_category = $path[2];
			else
				$current_category = 'a';
		}
		elseif ($path[0] == 'shows' && $path[1] == 'category') { // current shows with category
			$is_current_shows = true;
			$is_alphabetical = false;
			if ($path[2])
				$current_category = $path[2];
			else
				$current_category = '';
		}
		else { // current shows alphabetical
			$is_current_shows = true;
			$is_alphabetical = true;
			if ($path[1])
				$current_category = $path[1];
			else
				$current_category = 'a';
		}

		// build the 'viewing' section
		$content = '<div class="viewing">Viewing:';
		if ($is_current_shows){
			$content .= '<span class="current">Current Shows</span>';
			if ($is_alphabetical)
				$content .= '<span class="past"><a href="/shows/past-shows">Past Shows</a></span>';
			else
				$content .= '<span class="past"><a href="/shows/past-shows/category/'.$current_category.'">Past Shows</a></span>';
		}
		else{
			if ($is_alphabetical)
				$content .= '<span class="current"><a href="/shows">Current Shows</a></span>';
			else
				$content .= '<span class="current"><a href="/shows/category/'.$current_category.'">Current Shows</a></span>';
			$content .= '<span class="past">Past Shows</span>';
		}
		$content .= '</div>';

		// build the 'sort by' section
		$content .= '<div class="sort-by">Sort By:';
		if ($is_alphabetical){
			$content .= '<span class="alphabetical">Alphabetical</span>';
			if ($is_current_shows)
				$content .= '<span class="category"><a href="/shows/category">Category</a></span>';
			else
				$content .= '<span class="category"><a href="/shows/past-shows/category">Category</a></span>';
		}
		else{
			if ($is_current_shows)
				$content .= '<span class="alphabetical"><a href="/shows">Alphabetical</a></span>';
			else
				$content .= '<span class="alphabetical"><a href="/shows/past-shows">Alphabetical</a></span>';
			$content .= '<span class="category">Category</span>';
			$content .= _mnnshow_block_category_dropdown($is_current_shows, $current_category);
		}
		$content .= '</div>';

		// build the alphabet links (if necessary)
		if ($is_alphabetical){
			$content .= _mnnshow_block_alphabet_links($is_current_shows, $current_category);
		}

		return $content;
	}

	function _mnnshow_block_publisher_info(){
		$path = drupal_get_path_alias($_GET['q']);
		$path = explode('/', $path);
		if ($path[0] == 'show-info' && is_numeric($path[1])) {
			$sql = 'SELECT DISTINCT s.project_id, p.producer_id, p.display_name, p.email, p.phone_primary ';
			$sql .= 'FROM {ac_report_project_cache} s INNER JOIN {ac_report_producer_cache} p ';
			$sql .= 'ON s.exec_producer_id = p.producer_id ';
			$sql .= 'WHERE s.project_id = "' . $path[1] . '"';
			$sql = db_rewrite_sql($sql);

			$result = db_query($sql);
			while ($row = db_fetch_object($result)) {
				if ($row->display_name)
					$content = '<div class="name"><span>'. t('Produced by') .'</span><br />'. $row->display_name .'</div>';
				if ($row->website)
					$content .= '<div class="website"><span>'. t('Website') .'</span><br />'. $row->website .'</div>';
				if ($row->email)
					$content .= '<div class="email"><span>'. t('Email by') .'</span><br /><a href="mailto:'. $row->email .'">'. $row->email .'</a></div>';
				if ($row->phone_primary)
					$content .= '<div class="phone"><span>'. t('Phone') .'</span><br />'. $row->phone_primary .'</div>';
			}

			return $content;
		}
		else {
			return t('Producer info not found');
		}
	}

	function _mnnshow_show_current_list($query, $count_query, $category) {
		$pager_num = 0;
		$result = pager_query(db_rewrite_sql($query), 15, $pager_num, $count_query);
		$content = '';
		if (!is_null($category))
			$content .= '<h2>'.$category.'</h2>';
		while ($row = db_fetch_object($result)) {
			$title = $row->title; //ucwords(strtolower($row->title));
			$href = _mnnshow_get_show_href($title, $row->project_id);

			$content .= '<div class="row">';
			$content .= '<h3 class="title"><a href="/'. $href .'">'. $title .'</a></h3>';
			$content .= '<div class="category">'. $row->topic .'</div>';
			$content .= '<div class="meta"><span class="channel">'. $row->channel .'</span>';
			if ($row->start_time){
				$content .= '<span class="next-airing">Next Airing: '. date("D, M j, Y \a\\t g:ia T", strtotime($row->start_time)) .'</span></div>';
			}
			else {
				$content .= '<span class="next-airing">Next Airing: There are no scheduled airings for this show.</span></div>';
			}
			$content .= '<div class="content">' . $row->description . '</div>';
			$content .= '</div>';
		}
		return $content . theme('pager', NULL, 15, $pager_num);
	}

	function _mnnshow_show_past_list($query, $count_query, $category) {
		$pager_num = 0;
		$result = pager_query(db_rewrite_sql($query), 45, $pager_num, $count_query);
		$content = '';
		if (!is_null($category))
			$content .= '<h2>'.$category.'</h2>';
		$items = array();
		while ($row = db_fetch_object($result)) {
			$title = $row->title; //ucwords(strtolower($row->title));
			$href = _mnnshow_get_show_href($title, $row->project_id);

			$items[] = '<a href="/'. $href .'">'. $title .'</a>';
		}

		$col1 = $col2 = $col3 = floor(count($items) / 3);
		if (count($items) % 3 == 2)
			$col2++;
		if (count($items) % 3 == 1)
			$col1++;
		$content .= '<div class="col1">';
		for ($i = 0; $i < $col1; $i++){
			$content .= '<div class="item-'.$i.'">'.$items[$i].'</div>';
		}
		$content .= '</div>';
		$content .= '<div class="col2">';
		for ($i = $col1; $i < $col1 + $col2; $i++){
			$content .= '<div class="item-'.$i.'">'.$items[$i].'</div>';
		}
		$content .= '</div>';
		$content .= '<div class="col3">';
		for ($i = $col1 + $col2; $i < $col1 + $col2 + $col3; $i++){
			$content .= '<div class="item-'.$i.'">'.$items[$i].'</div>';
		}
		$content .= '</div>';

		return $content . theme('pager', NULL, 45, $pager_num);
	}

	function _mnnshow_block_alphabet_links($is_current_shows, $current_category) {
		$links = array('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z');
		$content = '<div class="alphabet">';
		foreach ($links as $link) {
			$content .= '<span>';
			if (strtolower($current_category) == $link){
				$content .= strtoupper($link);
			}
			else {
				if ($is_current_shows)
					$l = '/shows/';
				else
					$l = '/shows/past-shows/';
				$content .= '<a href="'.$l.$link.'">'.strtoupper($link).'</a>';
			}
			$content .= '</span>';
		}
		$content .= '</div>';

		return $content;
	}

	function _mnnshow_block_category_dropdown($is_current_shows, $current_category) {
		global $base_root;
		if (!$is_current_shows)
			$past_url = 'past-shows/';
		$categories = _mnnshow_get_categories();
		$js = 'location.href=\''. $base_root .'/shows/'. $past_url . 'category/\' + this.options[this.selectedIndex].value;';
		$select = '<select name="category" size="1" onchange="'.$js.'" onmouseup="this.focus()">';
		$select .= '<option value="">All</option>';
		foreach ($categories as $cat => $cat_value){
			if ($cat == $current_category) { $selected = ' selected="selected"'; } else { $selected = ''; }
			$select .= '<option value="'. $cat .'"'. $selected .'>'. $cat_value .'</option>';
		}
		$select .= '</select>';
		return $select;
	}

	function _mnnshow_get_categories(){
		$sql = 'SELECT DISTINCT s.topic ';
		$sql .= 'FROM {ac_report_project_cache} s ';
		$sql .= 'ORDER BY s.topic ASC ';
		$result = db_query(db_rewrite_sql($sql));
		$ret = array();
		while ($row = db_fetch_object($result)){
			if (!is_null($row->topic)){
				$url_cat = _mnnshow_url_feiendly_title($row->topic);
				$ret[$url_cat] = $row->topic;
			}
		}
		return $ret;
	}

	function _mnnshow_get_show_href($title, $id) {
		$url_title = _mnnshow_url_feiendly_title($title);
		$href = 'show-info/' . $id . '/' . $url_title;
		return $href;
	}

	function _mnnshow_url_feiendly_title($title){
		// remove all non-alphanumeric characters, then remove leading/trailing spaces
		$url_title = trim(preg_replace("/[^A-Za-z0-9\/ ]/", '', strtolower($title)));
		// replace spaces with dashes
		$url_title = preg_replace("/[\/ ]/", '-', $url_title);

		return $url_title;
	}